services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - .:/var/www/html
    links:
      - db
  db:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vgel
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
volumes:
  db_data:
