openapi: 3.0.0
info:
  title: 'Vide grenier en ligne API'
  description: 'Une API pour gérer les articles et les villes du vide grenier en ligne'
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: "Affiche la liste des articles / produits pour la page d'accueil"
      operationId: e35803db7dc3263e3622538255f4c890
      parameters:
        -
          name: sort
          in: query
          description: 'Critère de tri des produits (views ou date)'
          required: false
          schema:
            type: string
            enum:
              - views
              - date
        -
          name: latitude
          in: query
          description: 'Latitude pour la géolocalisation'
          required: false
          schema:
            type: number
            format: float
        -
          name: longitude
          in: query
          description: 'Longitude pour la géolocalisation'
          required: false
          schema:
            type: number
            format: float
        -
          name: radius
          in: query
          description: 'Rayon en kilomètres pour la géolocalisation'
          required: false
          schema:
            type: number
            format: float
        -
          name: search
          in: query
          description: 'Recherche dans les articles'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Fetches products'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { id: { type: integer }, name: { type: string }, description: { type: string }, published_date: { type: string }, user_id: { type: integer }, views: { type: integer }, picture: { type: string }, ville_id: { type: integer } }
                  type: object
  /api/userproducts:
    get:
      summary: 'Affiche la liste des articles / produits pour un utilisateur'
      operationId: d0cf98fe01d84a4748d9fc5a59ff48a0
      parameters:
        -
          name: sort
          in: query
          description: 'Critère de tri des produits (views ou date)'
          required: false
          schema:
            type: string
            enum:
              - views
              - date
      responses:
        '200':
          description: 'Fetches user products'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { id: { type: integer }, name: { type: string }, description: { type: string }, published_date: { type: string }, user_id: { type: integer }, views: { type: integer }, picture: { type: string }, ville_id: { type: integer } }
                  type: object
  /api/cities:
    get:
      summary: 'Recherche dans la liste des villes'
      operationId: a0f15af3ba703749030849d863dcb260
      responses:
        '200':
          description: 'Search cities'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { id: { type: integer }, name: { type: string } }
                  type: object
  /donatePerUser:
    get:
      summary: "Affiche le nombre d'articles donnés par utilisateur"
      operationId: d07a65470a6f856bd740975bea03e47a
      responses:
        '200':
          description: 'Fetches statistics'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { username: { type: string }, nombre_d_articles: { type: integer } }
                  type: object
  /donatePerCity:
    get:
      summary: "Affiche le nombre d'articles donnés par ville"
      operationId: 235c172bf85cf1b4541ae30a7c847c44
      responses:
        '200':
          description: 'Fetches statistics'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { city: { type: string }, nombre_d_articles: { type: integer } }
                  type: object
  /mostViewed:
    get:
      summary: 'Affiche les articles les plus vus'
      operationId: 4303eca040967038f60faddd2f713426
      responses:
        '200':
          description: 'Fetches statistics'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { name: { type: string }, views: { type: integer } }
                  type: object
  /mostContacted:
    get:
      summary: 'Affiche les articles qui découle sur un contact'
      operationId: ae0d05dcdac2596ff012b0aba6b600a0
      responses:
        '200':
          description: 'Fetches statistics'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { name: { type: string }, contact_count: { type: integer } }
                  type: object
  /getUserCount:
    get:
      summary: "Affiche le nombre d'utilisateurs"
      operationId: 13e3f3266c4ee595f50dd1646b715f73
      responses:
        '200':
          description: 'Fetches statistics'
          content:
            application/json:
              schema:
                type: array
                items:
                  properties: { user_count: { type: integer } }
                  type: object
